# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "LetsEncrypt Mythic Beasts"
description: "Create and update LetsEncrypt certificates using Mythic Beasts DNS"
version: "1.0.40"
slug: "encrypted_beasts"
url: "https://github.com/danieldurrans/haos-addons/tree/main/encrypted_beasts"
init: false
boot: auto
startup: once
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl:rw
options:
  contact_email: null
  domain: null
  api_key: null
schema:
  contact_email: email
  domain: str
  api_key: password
